- alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data_template: 
        title: 'New Home Assistant Release'
        target: 'device/Samsung_alco' #See Pushbullet component for usage
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."