- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "Garden2/cmnd/SetOption19"
        payload: "1"
    - service: mqtt.publish
      data:
        topic: "Garden2/cmnd/state"
        payload: "" 
