
#- platform: ffmpeg
#  name: Oprit
#  input: -rtsp_transport tcp -i !secret opritcam_url
#  input: -rtsp_transport tcp -i rtsp://192.168.1.155:554/user=admin&password=@PASSWORD&channel=1&stream=1.sdp?

# - platform: onvif
  # username: !secret opritcam_name
  # password: !secret opritcam_pass
  # port: 8080
  # host: !secret opritcam_url
  # profile: 1
  # name: Oprit
  
#- platform: onvif
#  username: !secret deurcam_name
#  password: !secret deurcam_pass
#  port: 8080
##  host: !secret deurcam_url
#  #profile: 2
#  name: Deur

# - platform: onvif
  # username: !secret tuincam_name
  # password: !secret tuincam_pass
  # port: 8899
  # host: !secret tuincam_url
  # profile: 2
  # name: tuin
  

- platform: generic
  name: voordeur
  #stream_source: rtsp://192.168.1.151:554/user=nano&password=@PASSWORD&channel=1&stream=1.sdp?
  stream_source: rtsp://192.168.1.151:554
  still_image_url: http://192.168.1.151:1099/web/auto.jpg?-usr=nano&@Pass
  username: !secret deurcam_name
  password: !secret deurcam_pass
