# - platform: wunderground
  # api_key: !secret wunderground
  # monitored_conditions:
    # - alerts
    # - weather_1d
    # - precip_1d
# #TODO:
#Platform: emoncms 
#coinbase https://www.home-assistant.io/components/sensor.emoncms/

# Interval records from energymonitor
- platform: emoncms
  api_key: !secret Emoncms_API
  url: !secret Emoncms_URL
  scan_interval: 30
  id: 1
  unit_of_measurement: "W" 
  include_only_feed_id:
    - 1
    - 2
    - 3
    - 6
    - 7
    - 11
    - 15
    - 19
    - 20
    - 27
    - 28
    - 29
    - 31
    - 33
    - 34
    
  sensor_names:
    1: "Voltage AC"
    2: "House use"
    7: "Solar Zuid"
    17: "Kookplaat"
    19: "Stroom import"
    22: "Temperatuur water aanvoer"
    23: "Temperatuur kruipruimte"
    27: "Solar Serre"
    31: "Solar totaal"

# Day records from energymonitor
- platform: emoncms
  api_key:  !secret Emoncms_API
  url: !secret Emoncms_URL
  id: 2
  scan_interval: 1800
  unit_of_measurement: "KWHD" 
  include_only_feed_id:
    - 10
    - 15
  sensor_names:
    15: "KWHd total"
    33: "KWHd Solar"
    



#weerstation
- platform: rfxtrx
  automatic_add: True
  devices:
    0b550200f1000000006d1c79:
      name: Regen
      data_type:
      - Rain rate
    0a52021464010083430070:
      name: Tuin
      data_type:
      - Humidity
      - Temperature
    0a520203b601005b620359:
      name: Tuin2
      data_type:
      - Humidity
      - Temperature
    105602046c0000ca001e00166874205259:
      name: Wind
      data_type:
      - Wind direction
      
#- platform: google_travel_time
#  name: Drive_time_to_work
#  api_key: !secret google_travel
#  origin: place_id:
#  destination: place_id:
#  options:
#    arrival_time: '09:15:00'
- platform: nederlandse_spoorwegen
  email: !secret ns_user
  password: !secret ns_password
  routes:
    - name: Apeldoorn-Amsterdam
      from: Apd
      to: Asd
    - name: Amsterdam-Apeldoorn
      from: Asd
      to: Apd
  #    via: Zl
  
# - platform: template
  # sensors:
    # cpu:
      # friendly_name: 'CPU Utilization'
      # value_template: '{{states.sensor.processor_use.state | float(1) }}'
      # unit_of_measurement: '%'
    # ram:
      # friendly_name: 'RAM Utilization'
      # value_template: '{{states.sensor.memory_use_percent.state | float(1) }}'
      # unit_of_measurement: '%'
    # disk:
      # friendly_name: 'Disk Utilization'
      # value_template: '{{states.sensor.disk_use_percent.state | float(1) }}'
      # unit_of_measurement: '%'
- platform: command_line
  name: CPU Temperature
  scan_interval:
   seconds: 10
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.0018) | round(1) +32 }}'
  unit_of_measurement: "°F"
#- platform: command_line
#  name: air_quality
#  scan_interval:
#    minutes: 10
#  command: 'curl -X GET -H "Content-type: application/json" -H "Accept: application/json" "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=38016&distance=25&API_KEY=BB4DF57E-645A-4867-935F-3BC241441002"'
#  value_template: '{{value_json[0]["AQI"]}}'
- platform: systemmonitor
  scan_interval:
    seconds: 10
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_5m

- platform: dnsip
  scan_interval: 300
- platform: time_date
  display_options:
    - 'time'

#postnl
- platform: postnl
  username: !secret POSTNL_USERNAME
  password: !secret POSTNL_PASSWORD